name: Staging Checks

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  format-js:
    name: JS Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: pycon-website-template
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.16"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-14.16-${{ hashFiles('pycon-website-template/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-14.16-${{ hashFiles('pycon-website-template/package.json') }}
      - name: Install node dependencies
        run: |
          cd pycon-website-template/
          npm install --only=dev
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd pycon-website-template/
          npm run lint
